export { Matrix } from 'coord-matrix2d'
export { MatrixDenser } from './utils/MatrixDenser'
export { MatrixTrainer } from './utils/MatrixTrainer'
export { MatrixExtractor } from './utils/MatrixExtractor'
export { MatrixTransformer } from './utils/MatrixTransformer'